# Generated by Django 5.0.7 on 2024-08-04 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_origenmovimiento_tipometa_ahorro_meta_alcanzada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorro',
            name='tipo_ahorro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='finanzas.tipoahorro'),
            preserve_default=False,
        ),
    ]
