# Generated by Django 5.0.7 on 2024-08-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_ahorro_tipo_ahorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorro',
            name='cantidad_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad inicial'),
        ),
    ]
